### ISSUE TITLE
Patches untested on various versions

### ISSUE THREAD

**Issue by HookedBehemoth** [HookedBehemoth/bitmap-printer#1]
Please comment below if this works on an undocumented system version.
See [here](https://github.com/HookedBehemoth/bitmap-printer/blob/master/README.md)

**Comment by znxDomain** [comment]
Works good on HOS 8.0.1/AMS 0.10.1

**Comment by HookedBehemoth** [comment]
More versions might come in the future but for now all available versions are tested.

**Comment by janAkali** [comment]
everything works on 10.2.0 | AMS 0.14.4

**Comment by jelbo** [comment]
Does not seem to work on 18.0.1. Nothing happens when pressing the screenshot button and when holding it, it says 'Unable to take a video capture now.'

**Comment by masagrator** [comment]
> Does not seem to work on 18.0.1. Nothing happens when pressing the screenshot button and when holding it, it says 'Unable to take a video capture now.'

Did you install sysmodule and try to check if files are created on sdcard? There is no notification when you are taking screenshot with it.

**Comment by jelbo** [comment]
> > Does not seem to work on 18.0.1. Nothing happens when pressing the screenshot button and when holding it, it says 'Unable to take a video capture now.'
> 
> Did you install sysmodule and try to check if files are created on sdcard? There is no notification when you are taking screenshot with it.

It works! Thank you. 18.0.1 | AMS 1.7.0. I expected a notification and I didn't look in the right folder. The .bmp files were in `\emuMMC\RAW1\Nintendo\Album\Bitmaps\`.

**Comment by impeeza** [comment]
Tested Patches for FW 19 with Atmosphère 1.8.0 and so far everything working perfect.
