### ISSUE TITLE
Unfortunately not working on the latest 14.1.2 firmware

### ISSUE THREAD

**Issue by DigitalSeibutsu** [HookedBehemoth/bitmap-printer#12]

**Comment by HookedBehemoth** [comment]
Weird. I assumed this was because vi was updated and it needed new patches. It wasn't.
Make sure you downloaded the newest version https://github.com/HookedBehemoth/bitmap-printer/releases

I'll investigate further when my switch is charged.

**Comment by HookedBehemoth** [comment]
works on my machine
