### ISSUE TITLE
Feature request: save full resolution

### ISSUE THREAD

**Issue by mariomadproductions** [HookedBehemoth/bitmap-printer#15]
Could support for taking screenshots at full resolution be added? As I understand it, screenshots are still fixed at 1280x720, like with an unmodded system.

**Comment by HookedBehemoth** [comment]
Not possible with this.
I'm reading from an internal screenshot buffer which is fixed to this resolution.
So far I couldn't motivate myself to figure out how to obtain the framebuffer directly.

**Comment by mariomadproductions** [comment]
Okay, thanks for explaining.
