### ISSUE TITLE
Bitmap-Printer crashes on 17.0.0 [AMS 1.6.2]

### ISSUE THREAD

**Issue by AsteroidPizza39** [HookedBehemoth/bitmap-printer#19]
With the latest switch firmware update and atmosphere version, and the latest version of bitmap printer installed, my switch crashes when booting atmosphere. Here's the crash screen:
![image](https://github.com/HookedBehemoth/bitmap-printer/assets/45804670/3348f5dc-8e52-4f33-b361-5ca5a17ade82)

**Comment by HookedBehemoth** [comment]
That's some other homebrew that crashes. Reopen if it still occurs with that one removed.

**Comment by HookedBehemoth** [comment]
>SM_OutOfSessions
You just seem to have too much shit installed.
