### ISSUE TITLE
Saving Docked Quality Screenshots

### ISSUE THREAD

**Issue by AsteroidPizza39** [HookedBehemoth/bitmap-printer#20]
I've been trying to figure out where screenshot size is determined, and I found a potential clue [here in stratosphere](https://github.com/Atmosphere-NX/Atmosphere/blob/872c18c501cdad9866524d7be6e038cd9c332232/libraries/libstratosphere/include/stratosphere/capsrv/server/capsrv_server_config.hpp#L22). It looks like [this previous issue](https://github.com/HookedBehemoth/bitmap-printer/issues/15) reached a dead end, so I thought I might point in a possible right direction.
![image](https://github.com/HookedBehemoth/bitmap-printer/assets/45804670/4defc478-ddd6-49ca-b6fa-d3fdf0f9c616)

**Comment by HookedBehemoth** [comment]
There are fixed size memory buffers inside vi, the sysmodule that captures the screenshot.

**Comment by HookedBehemoth** [comment]
Closing this as "not planed"
Maybe a future HOS version will allow for it.
