### ISSUE TITLE
Bitmap Printer not working on 17.0.1

### ISSUE THREAD

**Issue by lontrafag** [HookedBehemoth/bitmap-printer#21]
Module is showing on Tesla menu, but no effect after toggle on.

**Comment by janAkali** [comment]
quick fix until new release is published: download this patch and put it into `atmosphere/exefs_patches/vi_patches`: 
https://github.com/HookedBehemoth/bitmap-printer/raw/master/patches/34D15383767E313EE76F1EE991CD00AD2BF8C62A.ips

**Comment by masagrator** [comment]
This is because patch for 17.0.0+ was not added to release, is in repository.

**Comment by lontrafag** [comment]
Gotcha, it's working now!
