### ISSUE TITLE
Does Not Work on 18.0.1 and Above

### ISSUE THREAD

**Issue by heare2code** [HookedBehemoth/bitmap-printer#23]
I noticed that any of the screenshots I've been taking with the module on doesn't save any files in the Bitmap folder or any other folder. I noticed this a few months ago after I updated to 18.0.1 but I thought it was some issue on my end, but after reinstalling it a few days go on 18.1.0, it still doesn't save anything. Weirdly it doesn't show a screenshot notification, nor saves a jpg in the normal Album folder, nor let me record as if it was working just not saving the screenshot.

**Comment by janAkali** [comment]
Latest release (1.3.0d) does work for me on HOS: 18.0.1 AMS: 1.7.0
