### ISSUE TITLE
Plan for updater patches to 19.0.0

### ISSUE THREAD

**Issue by CostelaCNX** [HookedBehemoth/bitmap-printer#24]
Hello, you plan update patches to works on HOS 19.0.0? Tks in advice!

**Comment by HookedBehemoth** [comment]
Yes

**Comment by HookedBehemoth** [comment]
Updated the patch but didn't test yet. You'll have to wait for Atmosphère anyway.
https://github.com/HookedBehemoth/bitmap-printer/releases/tag/v1.3.0e
