### ISSUE TITLE
bitmap-printer not always called

### ISSUE THREAD

**Issue by MegaPramuk** [HookedBehemoth/bitmap-printer#6]
When I was playing Animal Crossing to make several screenshots (e.g. a special character's dialogue), some textbox screenshots were made by HOS, then bitmap-printer and then HOS again (in that order, in just a minute of making screenshots).
Running AMS 0.12.0 on FW 10.0.0.
If you need further info, I'll happily provide.

**Comment by HookedBehemoth** [comment]
To save some memory space I only read 10 lines at a time and in my testing it takes ~3 seconds for a screenshot to be saved.
I don't think this is game related in any way.

**Comment by MegaPramuk** [comment]
Okay, seems like it is related to sys-con.
Just compiled latest master (https://github.com/HookedBehemoth/bitmap-printer/commit/dd877c89903ec64a29fa6fc5fe7a5b8e8cc4aaba) to check out timestamps and it didn't work at first.
Renamed sys-con's folder, reboot, checked again and it worked (with the proper timestamps!).
Changed back and now it seems to work (at least in the home menu)?
I don't get it, but I'm closing it now since it seems not to be bitmap-printer's fault.
