### ISSUE TITLE
11.0.1

### ISSUE THREAD

**Issue by ghost** [HookedBehemoth/bitmap-printer#7]
bitmap-printer seems to require another update for this firmware, the default photo functionality still happens when bitmap-printer is activated

**Comment by HookedBehemoth** [comment]
mind testing that one for me? Didn't update yet.
[patch.zip](https://github.com/HookedBehemoth/bitmap-printer/files/5682502/patch.zip)

**Comment by ghost** [comment]
> 
> 
> mind testing that one for me? Didn't update yet.
> [patch.zip](https://github.com/HookedBehemoth/bitmap-printer/files/5682502/patch.zip)

That's working, thanks!

**Comment by HookedBehemoth** [comment]
Drafted a new release with that patch. Thanks for testing. 👍🏻
