### ISSUE TITLE
Not Working on HOS 11.0.1/AMS M.18.0

### ISSUE THREAD

**Issue by znxDomain** [HookedBehemoth/bitmap-printer#8]
Only getting default behavior, not saving bitmaps on HOS 11.0.1 with AMS M.18.0.  

I'll try updating Atmosphere right now.

**Comment by znxDomain** [comment]
Just update to HOS 11.0.1 with AMS M.18.1 and it is still not working.

**Comment by HookedBehemoth** [comment]
boot2 start issues fixed in the last release.
