### ISSUE TITLE
Doesn't work in latest atmosphere

### ISSUE THREAD

**Issue by BetterWaifus** [HookedBehemoth/bitmap-printer#9]
Bitmap Printer isnt working in atmosphere 19.1 I'm on firmware version 12.0.1 right now.

**Comment by HookedBehemoth** [comment]
https://github.com/HookedBehemoth/exefs_patches/blob/122077443ca3a481e7f041c4f0d233b1a6e2814e/atmosphere/exefs_patches/vi_debug/B295D3A8F8ACF88CB0C5CE7C0488CC5511B9C389.ips

Drag that patch into the exefs_patches/vi_debug folder.
Got sidetracked with things that are actually fun.

**Comment by BetterWaifus** [comment]
Worked thanks.

**Comment by Heartbeat-Heartbreak** [comment]
Is there an update for 13.0？
